### ISSUE TITLE
Permission error using NEW_RELIC_LOG

### ISSUE THREAD

**Issue by copelco** [caktus/margarita#105]
The [README](https://github.com/caktus/margarita/blob/develop/README.rst#new-relic) says to use define NEW_RELIC_LOG like so:

```
# project.sls
env:
    NEW_RELIC_LOG: "/var/log/newrelic/agent.log"
```

However, supervisord app's instance throws this permission error:

```
2016-02-07 16:41:51,549 (21580/MainThread) newrelic ERROR - Falling back to stderr logging as unable to create log file '/var/log/newrelic/agent.log'.
Traceback (most recent call last):
  File "/var/www/<proj>/env/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/common/log_file.py", line 79, in initialize_logging
    _initialize_file_logging(log_file, log_level)
  File "/var/www/<proj>/env/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/common/log_file.py", line 51, in _initialize_file_log
    handler = logging.FileHandler(log_file)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/newrelic/agent.log'
```

Should this be using syslog now?

**Comment by vkurup** [comment]
Yes, I had been using a log file in our old project log directory to avoid the permission denied error.

Looking at this, I wonder if we can just omit the setting entirely, and then newrelic would log to syslog automatically, since our LOGGING setting logs to the console, which is sent to syslog by supervisor: https://discuss.newrelic.com/t/logging-to-syslog/14929

**Comment by vkurup** [comment]
I just tested that theory on RescueID and it was successful. Unsetting the 'NEW_RELIC_LOG' variable resulted in New Relic logs going to syslog.

**Comment by vkurup** [comment]
This has been fixed now in margarita and in the documentation.
