### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/file_lists/gitfs/.feature/postgis-states.w'

### ISSUE THREAD

**Issue by victor-rocha** [caktus/margarita#22]
I just noticed that while running a highstate this error gets logged in master's log file.
This does not not prevent from successfully running a highstate but why it is being logged?

2014-03-08 14:56:44,153 [salt.master      ][ERROR   ] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/master.py", line 1637, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/pymodules/python2.7/salt/fileserver/__init__.py", line 370, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/pymodules/python2.7/salt/fileserver/gitfs.py", line 475, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/pymodules/python2.7/salt/fileserver/gitfs.py", line 452, in _file_lists
    __opts__, form, list_cache, w_lock
  File "/usr/lib/pymodules/python2.7/salt/fileserver/__init__.py", line 42, in check_file_list_cache
    if not os.path.isfile(list_cache) and _lock_cache(w_lock):
  File "/usr/lib/pymodules/python2.7/salt/fileserver/__init__.py", line 23, in _lock_cache
    os.mkdir(w_lock)
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/file_lists/gitfs/.feature/postgis-states.w'

**Comment by mlavin** [comment]
This warning is a non-issue. Just another Salt weirdness so I'm going to close.
