### ISSUE TITLE
Pip upgrade issue

### ISSUE THREAD

**Issue by daaray** [caktus/margarita#35]
On a newly provisioned 12.04 box with python 2.7, with or without this change that pins setuptools (https://github.com/caktus/margarita/commit/5ffd6a7c8ae0d1be8723807029512a813def2533), the following error occurs on the initial `fab vagrant deploy`:

```
2015-01-08 00:47:25,527 [salt.loaded.int.module.cmdmod][ERROR   ] Command '/usr/bin/pip freeze' failed with return code: 2
2015-01-08 00:47:25,528 [salt.loaded.int.module.cmdmod][ERROR   ] stderr: Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 68, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 156, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='AssertionError
```

ssh'ing into the box reveals:

```
daaray@precise32:/var/log/salt$ sudo pip --version
pip 1.0 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

I can work through this by manually upgrading pip at the command line and the do another deploy

```
daaray@precise32:/var/log/salt$ sudo pip install pip -U
...
daaray@precise32:/var/log/salt$ sudo pip --version
pip 6.0.6 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

I am uncertain as to why it is not upgrading itself without failing.

**Comment by vkurup** [comment]
I'm not certain, but I think this can be closed now. I had seen this error in the past, but not on recent projects.

**Comment by yesimon** [comment]
Although I don't use margarita - I found this issue while googling. The default version of pip packaged on ubuntu 15.04 is still 1.5.6. https://launchpad.net/ubuntu/+source/python-pip. I still had to do something like this to get the a working pip.
